export type GameItemAssetKey =
  | "foodBowl"
  | "treatPlate"
  | "salmonBites"
  | "chickenJerky"
  | "pumpkinCookie"
  | "berryYogurt"
  | "sweetPotatoChew"
  | "tunaCrunch"
  | "duckBiscuit"
  | "cheesePuff"
  | "appleBiscuit"
  | "milkPupCup"
  | "toyBall"
  | "plushToy"
  | "petBed"
  | "tinyHouse"
  | "flowerPot"
  | "flowerPotSeed"
  | "flowerPotSprout"
  | "flowerPotLeafy"
  | "flowerPotBloom"
  | "leafyPlant"
  | "cloverSprout"
  | "cloverLeafy"
  | "cloverBloom"
  | "hangingLantern"
  | "smallLamp"
  | "wateringCan"
  | "drinkWaterBowl"
  | "pondTile"
  | "steppingStone"
  | "rewardPouch"
  | "giftBox"
  | "coin"
  | "gem"
  | "seasonalFlowers"
  | "springPatchSprout"
  | "springPatchLeafy"
  | "springPatchBloom"
  | "bone"
  | "cushion"
  | "doghouse"
  | "gift"
  | "lantern"
  | "bath";

export const gameItemAssetByCatalogId: Record<string, GameItemAssetKey> = {
  item_food_bowl_basic: "foodBowl",
  item_treat_plate_biscuit: "treatPlate",
  item_bone_biscuit: "bone",
  item_salmon_bites: "salmonBites",
  item_chicken_jerky: "chickenJerky",
  item_pumpkin_cookie: "pumpkinCookie",
  item_berry_yogurt: "berryYogurt",
  item_sweet_potato_chew: "sweetPotatoChew",
  item_tuna_crunch: "tunaCrunch",
  item_duck_biscuit: "duckBiscuit",
  item_cheese_puff: "cheesePuff",
  item_apple_biscuit: "appleBiscuit",
  item_milk_pup_cup: "milkPupCup",
  item_toy_ball_mint: "toyBall",
  item_plush_toy_buddy: "plushToy",
  item_cushion_rose: "petBed",
  item_doghouse_sunny: "tinyHouse",
  item_flower_pot_sunny: "flowerPot",
  item_leafy_plant_clover: "leafyPlant",
  item_lantern_glow: "hangingLantern",
  item_small_lamp_glow: "smallLamp",
  item_watering_can_mint: "wateringCan",
  item_pond_tile_lily: "pondTile",
  item_stepping_stone_path: "steppingStone",
  item_reward_pouch_sunny: "rewardPouch",
  item_gift_ribbon: "giftBox",
  item_coin_sun: "coin",
  item_gem_pink: "gem",
  item_seasonal_flowers_spring: "seasonalFlowers",
  item_crystal_charm_premium: "gem"
};
