const LOCALES = [
  { code: "en-US", label: "English", short: "EN" },
  { code: "ko-KR", label: "한국어", short: "KO" },
  { code: "ja-JP", label: "日本語", short: "JA" },
  { code: "zh-TW", label: "繁體中文", short: "ZH" },
  { code: "de-DE", label: "Deutsch", short: "DE" },
  { code: "fr-FR", label: "Français", short: "FR" },
  { code: "pt-BR", label: "Português (Brasil)", short: "PT" },
  { code: "es-MX", label: "Español (México)", short: "ES" },
];

const SEO_ORIGIN = "https://mongchi.app";
const PAGE_PATHS = {
  landing: "/",
  privacy: "/privacy.html",
  terms: "/terms.html",
};
const OG_LOCALES = {
  "en-US": "en_US",
  "ko-KR": "ko_KR",
  "ja-JP": "ja_JP",
  "zh-TW": "zh_TW",
  "de-DE": "de_DE",
  "fr-FR": "fr_FR",
  "pt-BR": "pt_BR",
  "es-MX": "es_MX",
};

const LEGAL_LOADERS = {
  "en-US": () => import("./legal-resources/en-US.ts").then(({ enUS }) => enUS.legal),
  "ko-KR": () => import("./legal-resources/ko-KR.ts").then(({ koKR }) => koKR.legal),
  "ja-JP": () => import("./legal-resources/ja-JP.ts").then(({ jaJP }) => jaJP.legal),
  "zh-TW": () => import("./legal-resources/zh-TW.ts").then(({ zhTW }) => zhTW.legal),
  "de-DE": () => import("./legal-resources/de-DE.ts").then(({ deDE }) => deDE.legal),
  "fr-FR": () => import("./legal-resources/fr-FR.ts").then(({ frFR }) => frFR.legal),
  "pt-BR": () => import("./legal-resources/pt-BR.ts").then(({ ptBR }) => ptBR.legal),
  "es-MX": () => import("./legal-resources/es-MX.ts").then(({ esMX }) => esMX.legal),
};

const ENGLISH = {
  "meta.landing.title": "Mongchi - Your Pet, Living in Your Phone",
  "meta.landing.description": "Mongchi turns a favorite dog or cat photo into a pixel companion. Care, chat, play, and collect memories together. Chat replies are AI-generated.",
  "meta.privacy.title": "Privacy Policy - Mongchi",
  "meta.privacy.description": "What Mongchi collects, how your pet's photo is handled, and your privacy choices.",
  "meta.terms.title": "Terms of Service - Mongchi",
  "meta.terms.description": "The terms that govern your use of Mongchi, including AI content, photos, purchases, and acceptable use.",
  "a11y.skip": "Skip to content",
  "a11y.header": "Mongchi site header",
  "a11y.home": "Mongchi home",
  "a11y.primaryNav": "Primary navigation",
  "a11y.footerNav": "Footer navigation",
  "a11y.language": "Website language",
  "a11y.preview": "Mongchi app preview",
  "a11y.activities": "Mongchi activities",
  "a11y.features": "Mongchi feature stories",
  "a11y.principles": "Mongchi principles",
  "a11y.storeOptions": "Coming soon download options",
  "nav.start": "How it starts",
  "nav.life": "Life together",
  "nav.download": "Download",
  "nav.home": "Home",
  "nav.privacy": "Privacy",
  "nav.terms": "Terms",
  "hero.kicker": "One photo becomes a tiny friend.",
  "hero.title": "Your pet,<br />living in your phone.",
  "hero.lead": "Mongchi turns a favorite photo of your dog or cat into a tiny pixel companion to care for, chat with, and play with.",
  "hero.primary": "See availability",
  "hero.secondary": "See how it starts",
  "hero.release": "Coming soon on iOS and Android.",
  "hero.photoCaption": "One cherished photo",
  "marquee": "MEET · CARE · CHAT · PLAY · COLLECT MEMORIES · GROW CLOSER",
  "photo.kicker": "How it starts",
  "photo.title": "One favorite photo.<br />One pixel companion.",
  "photo.lead": "Choose a clear photo, meet your new pixel companion, and start making memories together.",
  "photo.caption": "Your favorite photo",
  "photo.note": "We use your photo to create your pixel companion.",
  "photo.policy": "Read the Privacy Policy.",
  "care.kicker": "A world that grows with you",
  "care.title": "Life together,<br />one tiny moment at a time.",
  "care.lead": "Care for your companion, chat and play together, and collect memories in a cozy, handcrafted pixel world.",
  "care.gentleTitle": "Care at your pace",
  "care.gentleBody": "No guilt if you miss a day.",
  "care.chatTitle": "Chat with your companion",
  "care.chatBody": "Chat replies are generated by AI and shaped by your pet's profile.",
  "care.memoryTitle": "Little memories",
  "care.memoryBody": "Collect finds from walks, new expressions, and special letters over time.",
  "download.kicker": "Mongchi is coming soon",
  "download.title": "Keep your pixel companion close.",
  "download.lead": "Drop in for a little care, a chat, or playtime, and collect memories along the way.",
  "download.coming": "Coming soon",
  "download.meta": "Free to download · iOS and Android",
  "footer.tagline": "Mongchi - Your Pet, Living in Your Phone",
  "footer.support": "Support",
  "footer.legalTitle": "Legal",
  "footer.privacy": "Privacy Policy",
  "footer.terms": "Terms of Service",
  "footer.delete": "Data deletion",
  "footer.language": "Language",
  "footer.copyright": "© 2026 DefineYou. All rights reserved.",
  "legal.back": "← Back to Mongchi",
  "legal.eyebrow": "Legal",
  "legal.overview": "The same plain-language overview shown in the app",
  "legal.fullEnglish": "Read the full English legal text",
  "legal.note": "This localized overview matches the in-app notice. The full English text below remains available as the complete published policy. Contact support if you need help in your language.",
  "legal.contact": "Questions? Email support",
  "privacy.heading": "Mongchi Privacy Policy",
  "privacy.updated": "Published July 12, 2026 · Full policy v1.1",
  "terms.heading": "Mongchi Terms of Service",
  "terms.updated": "Published July 12, 2026 · Full terms v1.0",
};

const COPY = {
  "en-US": ENGLISH,
  "ko-KR": {
    ...ENGLISH,
    "meta.landing.title": "Mongchi - 강아지·고양이 사진으로 만나는 픽셀 친구",
    "meta.landing.description": "Mongchi는 강아지나 고양이 사진 한 장을 AI 픽셀 친구로 만들어 줘요. 함께 돌보고, 대화하고, 놀며 소중한 추억을 모아 보세요.",
    "meta.privacy.title": "개인정보 처리방침 - Mongchi",
    "meta.privacy.description": "Mongchi가 처리하는 정보, 반려동물 사진의 사용 방식과 사용자의 선택을 확인하세요.",
    "meta.terms.title": "이용약관 - Mongchi",
    "meta.terms.description": "AI 콘텐츠, 사진, 구매와 허용되는 이용을 포함한 Mongchi 이용약관입니다.",
    "a11y.skip": "본문으로 건너뛰기",
    "a11y.header": "Mongchi 사이트 헤더",
    "a11y.home": "Mongchi 홈",
    "a11y.primaryNav": "주요 메뉴",
    "a11y.footerNav": "푸터 메뉴",
    "a11y.language": "웹사이트 언어",
    "a11y.preview": "Mongchi 앱 미리보기",
    "a11y.activities": "Mongchi 활동",
    "a11y.features": "Mongchi 기능 이야기",
    "a11y.principles": "Mongchi의 원칙",
    "a11y.storeOptions": "출시 예정 다운로드 옵션",
    "nav.start": "시작하는 법",
    "nav.life": "함께하는 일상",
    "nav.download": "다운로드",
    "nav.home": "홈",
    "nav.privacy": "개인정보",
    "nav.terms": "이용약관",
    "hero.kicker": "사진 한 장이 작은 친구가 돼요.",
    "hero.title": "우리 아이가,<br />휴대폰 속에 살아요.",
    "hero.lead": "Mongchi는 강아지나 고양이 사진 한 장을 함께 돌보고 대화하고 놀 수 있는 작은 픽셀 친구로 만들어 줘요.",
    "hero.primary": "출시 안내 보기",
    "hero.secondary": "시작하는 법 보기",
    "hero.release": "iOS와 Android에서 곧 만나요.",
    "hero.photoCaption": "소중한 한 장",
    "marquee": "만나요 · 돌봐요 · 대화해요 · 놀아요 · 추억을 모아요 · 더 가까워져요",
    "photo.kicker": "시작하는 법",
    "photo.title": "소중한 사진 한 장.<br />우리 아이를 닮은 픽셀 친구.",
    "photo.lead": "선명한 사진 한 장을 고르면 우리 아이의 모습이 작은 픽셀 친구가 돼요.",
    "photo.caption": "가장 좋아하는 사진",
    "photo.note": "사진은 우리 아이를 닮은 픽셀 친구를 만드는 데 사용돼요.",
    "photo.policy": "개인정보 처리방침 보기",
    "care.kicker": "우리 사이가 자라는 시간",
    "care.title": "함께하는 일상,<br />작은 순간을 하나씩.",
    "care.lead": "실제 앱 화면에서 우리 아이를 돌보고, 대화하고, 놀며 추억을 쌓는 일상을 미리 만나 보세요.",
    "care.gentleTitle": "다정한 리듬",
    "care.gentleBody": "하루를 놓쳐도 미안해하지 않아도 돼요.",
    "care.chatTitle": "우리 아이를 닮은 대화",
    "care.chatBody": "AI가 만든 답변이에요. 우리 아이를 닮은 친구와 다정하게 이야기해요.",
    "care.memoryTitle": "작은 추억",
    "care.memoryBody": "산책에서 발견한 것들, 여러 표정과 편지가 추억으로 쌓여요.",
    "download.kicker": "출시를 준비하고 있어요",
    "download.title": "우리 아이를 닮은 픽셀 친구를 만나 보세요.",
    "download.lead": "잠깐씩 안부를 나누고, 소중한 우리 아이를 가까이 느낄 수 있도록 만들었어요.",
    "download.coming": "출시 예정",
    "download.meta": "무료 다운로드 · iOS 및 Android",
    "footer.tagline": "Mongchi - 우리 아이가 휴대폰 속에 살아요",
    "footer.support": "고객지원",
    "footer.legalTitle": "정책",
    "footer.privacy": "개인정보 처리방침",
    "footer.terms": "이용약관",
    "footer.delete": "데이터 삭제",
    "footer.language": "언어",
    "legal.back": "← Mongchi로 돌아가기",
    "legal.eyebrow": "정책",
    "legal.overview": "앱과 동일한 쉬운 정책 요약",
    "legal.fullEnglish": "전체 영문 정책 보기",
    "legal.note": "이 번역 요약은 앱의 안내와 같습니다. 아래 전체 영문은 게시된 완전한 정책으로 계속 제공됩니다. 한국어 도움이 필요하면 고객지원으로 연락해 주세요.",
    "legal.contact": "문의가 있나요? 이메일 고객지원",
    "privacy.heading": "Mongchi 개인정보 처리방침",
    "privacy.updated": "2026년 7월 12일 게시 · 전체 정책 v1.1",
    "terms.heading": "Mongchi 이용약관",
    "terms.updated": "2026년 7월 12일 게시 · 전체 약관 v1.0",
  },
  "ja-JP": {
    ...ENGLISH,
    "meta.landing.title": "Mongchi｜愛犬・愛猫の写真がピクセルペットに",
    "meta.landing.description": "Mongchiは、愛犬や愛猫の写真一枚を小さなピクセルペットに変えるアプリです。お世話も、おしゃべりも、遊びも楽しみながら、毎日の思い出を集められます。",
    "meta.privacy.title": "プライバシーポリシー - Mongchi",
    "meta.privacy.description": "Mongchiが扱うデータ、ペットの写真の処理方法、利用者の選択について説明します。",
    "meta.terms.title": "利用規約 - Mongchi",
    "meta.terms.description": "AIコンテンツ、写真、購入、利用上のルールを含むMongchiの利用規約です。",
    "a11y.skip": "本文へ移動",
    "a11y.header": "Mongchiサイトヘッダー",
    "a11y.home": "Mongchiホーム",
    "a11y.primaryNav": "メインナビゲーション",
    "a11y.footerNav": "フッターナビゲーション",
    "a11y.language": "ウェブサイトの言語",
    "a11y.preview": "Mongchiアプリのプレビュー",
    "a11y.activities": "Mongchiでできること",
    "a11y.features": "Mongchiの機能紹介",
    "a11y.principles": "Mongchiの考え方",
    "a11y.storeOptions": "配信予定のストア",
    "nav.start": "はじまり",
    "nav.life": "一緒の毎日",
    "nav.download": "ダウンロード",
    "nav.home": "ホーム",
    "nav.privacy": "プライバシー",
    "nav.terms": "利用規約",
    "hero.kicker": "愛犬・愛猫の写真が、ピクセルペットに。",
    "hero.title": "うちの子が、<br />スマホの中で暮らす。",
    "hero.lead": "Mongchiは、お気に入りの一枚を、お世話やおしゃべり、遊びを楽しめる小さなピクセルペットに変えてくれます。",
    "hero.primary": "配信情報を見る",
    "hero.secondary": "はじめ方を見る",
    "hero.release": "iOSとAndroidで近日配信。",
    "hero.photoCaption": "大切な一枚",
    "marquee": "出会う · お世話 · おしゃべり · 遊ぶ · 思い出を集める · もっと仲良く",
    "photo.kicker": "はじまり",
    "photo.title": "大切な一枚から、<br />小さな相棒へ。",
    "photo.lead": "写真を選ぶと、小さな相棒に会えます。",
    "photo.caption": "お気に入りの写真",
    "photo.note": "選んだ写真は、ピクセルペットをつくるために使います。",
    "photo.policy": "プライバシーポリシーを見る",
    "care.kicker": "うちの子と過ごす毎日",
    "care.title": "毎日が、<br />思い出になる。",
    "care.lead": "お世話や遊び、おしゃべり。実際の画面も紹介\u2060します。",
    "care.gentleTitle": "自分のペースで",
    "care.gentleBody": "お休みする日があっても大丈夫。",
    "care.chatTitle": "うちの子らしいおしゃべり",
    "care.chatBody": "返事はAIがつくります。うちの子らしい返事\u2060です。",
    "care.memoryTitle": "小さな思い出",
    "care.memoryBody": "散歩で見つけたもの、いろんな表情、届いた手紙。思い出が少しずつ増えていきます。",
    "download.kicker": "うちの子との毎日、もうすぐ。",
    "download.title": "いつでも、一緒。",
    "download.lead": "ちょっとした時間に、お世話したり、おしゃべりしたり。大好きなうちの子に、いつでも会いに行けます。",
    "download.coming": "近日配信",
    "download.meta": "無料ダウンロード · iOS / Android",
    "footer.tagline": "Mongchi - うちの子がスマホの中で暮らす",
    "footer.support": "サポート",
    "footer.legalTitle": "法的情報",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
    "footer.delete": "データの削除",
    "footer.language": "言語",
    "legal.back": "← Mongchiに戻る",
    "legal.eyebrow": "法的情報",
    "legal.overview": "アプリと同じ、わかりやすい概要",
    "legal.fullEnglish": "英語の全文を読む",
    "legal.note": "この翻訳概要はアプリ内の案内と同じ内容です。下の英語全文は、公開された完全なポリシーとして引き続き閲覧できます。日本語でのサポートが必要な場合はお問い合わせください。",
    "legal.contact": "ご質問はメールサポートへ",
    "privacy.heading": "Mongchi プライバシーポリシー",
    "privacy.updated": "2026年7月12日公開 · 全文 v1.1",
    "terms.heading": "Mongchi 利用規約",
    "terms.updated": "2026年7月12日公開 · 全文 v1.0",
  },
  "zh-TW": {
    ...ENGLISH,
    "meta.landing.title": "Mongchi｜把毛孩照片變成像素夥伴",
    "meta.landing.description": "Mongchi會把一張喜歡的狗狗或貓咪照片變成像素夥伴，照顧牠、和牠聊天玩耍，一起收藏日常回憶。",
    "meta.privacy.title": "隱私權政策 - Mongchi",
    "meta.privacy.description": "了解Mongchi處理哪些資料、如何使用寵物照片，以及你擁有的選擇。",
    "meta.terms.title": "服務條款 - Mongchi",
    "meta.terms.description": "包含AI內容、照片、購買與使用規範的Mongchi服務條款。",
    "a11y.skip": "跳到主要內容",
    "a11y.header": "Mongchi網站頁首",
    "a11y.home": "Mongchi首頁",
    "a11y.primaryNav": "主要導覽",
    "a11y.footerNav": "頁尾導覽",
    "a11y.language": "網站語言",
    "a11y.preview": "Mongchi應用程式預覽",
    "a11y.activities": "Mongchi活動",
    "a11y.features": "Mongchi功能故事",
    "a11y.principles": "Mongchi原則",
    "a11y.storeOptions": "即將推出的下載選項",
    "nav.start": "如何開始",
    "nav.life": "一起生活",
    "nav.download": "下載",
    "nav.home": "首頁",
    "nav.privacy": "隱私權",
    "nav.terms": "條款",
    "hero.kicker": "一張照片，讓毛孩變身像素夥伴。",
    "hero.title": "你的毛孩，<br />住進手機裡。",
    "hero.lead": "Mongchi會把你喜歡的狗狗或貓咪照片，變成住進手機裡的像素夥伴。",
    "hero.primary": "準備迎接牠",
    "hero.secondary": "看看怎麼開始",
    "hero.release": "即將於 iOS 與 Android 推出。",
    "hero.photoCaption": "最愛的毛孩照片",
    "marquee": "相遇 · 照顧 · 聊天 · 玩耍 · 留下回憶 · 越來越親近",
    "photo.kicker": "從一張照片開始",
    "photo.title": "一張最愛的照片，<br />變成像素毛孩。",
    "photo.lead": "選一張清楚的毛孩照片，遇見牠的像素分身，從此每天相伴。",
    "photo.caption": "你最喜歡的照片",
    "photo.note": "照片會用來創造你的像素夥伴。",
    "photo.policy": "閱讀隱私權政策",
    "care.kicker": "和你一起成長的小世界",
    "care.title": "一起過日子，<br />收藏每個小回憶。",
    "care.lead": "看看實際 App 畫面，感受精心打造的像素世界。",
    "care.gentleTitle": "自在的步調",
    "care.gentleBody": "偶爾一天沒上線，也不用有壓力。",
    "care.chatTitle": "貼近牠個性的聊天",
    "care.chatBody": "聊天回覆由 AI 生成，也會參考毛孩的個性。",
    "care.memoryTitle": "小小回憶",
    "care.memoryBody": "散步途中的小發現、牠的表情和來信，慢慢累積成你們的回憶。",
    "download.kicker": "很快就能相見",
    "download.title": "把像素毛孩帶在身邊。",
    "download.lead": "隨時回來看看牠，讓心愛的毛孩一直陪在身邊。",
    "download.coming": "即將登上",
    "download.meta": "免費下載 · iOS 與 Android",
    "footer.tagline": "Mongchi - 你的毛孩住進手機裡",
    "footer.support": "支援",
    "footer.legalTitle": "法律資訊",
    "footer.privacy": "隱私權政策",
    "footer.terms": "服務條款",
    "footer.delete": "刪除資料",
    "footer.language": "語言",
    "legal.back": "← 返回Mongchi",
    "legal.eyebrow": "法律資訊",
    "legal.overview": "與應用程式相同的易讀概要",
    "legal.fullEnglish": "閱讀完整英文法律文字",
    "legal.note": "此翻譯概要與應用程式內的說明一致。下方完整英文內容仍是正式發布的完整政策。如需語言協助，請聯絡支援團隊。",
    "legal.contact": "有問題嗎？寄信給支援團隊",
    "privacy.heading": "Mongchi 隱私權政策",
    "privacy.updated": "發布於2026年7月12日 · 完整政策v1.1",
    "terms.heading": "Mongchi 服務條款",
    "terms.updated": "發布於2026年7月12日 · 完整條款v1.0",
  },
  "de-DE": {
    ...ENGLISH,
    "meta.landing.title": "Mongchi – Dein Haustier als Pixelbegleiter",
    "meta.landing.description": "Mongchi macht aus einem Foto deines Hundes oder deiner Katze einen Pixelbegleiter. Kümmere dich um ihn, chatte und spiele mit ihm und sammle gemeinsame Erinnerungen.",
    "meta.privacy.title": "Datenschutzerklärung - Mongchi",
    "meta.privacy.description": "Welche Daten Mongchi verarbeitet, wie das Foto deines Tieres behandelt wird und welche Wahlmöglichkeiten du hast.",
    "meta.terms.title": "Nutzungsbedingungen - Mongchi",
    "meta.terms.description": "Die Mongchi-Nutzungsbedingungen zu KI-Inhalten, Fotos, Käufen und zulässiger Nutzung.",
    "a11y.skip": "Zum Inhalt springen",
    "a11y.header": "Mongchi-Seitenkopf",
    "a11y.home": "Mongchi-Startseite",
    "a11y.primaryNav": "Hauptnavigation",
    "a11y.footerNav": "Fußnavigation",
    "a11y.language": "Websitesprache",
    "a11y.preview": "Mongchi-App-Vorschau",
    "a11y.activities": "Mongchi-Aktivitäten",
    "a11y.features": "Mongchi-Funktionen",
    "a11y.principles": "Mongchi-Grundsätze",
    "a11y.storeOptions": "Bald verfügbare Downloads",
    "nav.start": "So beginnt es",
    "nav.life": "Gemeinsamer Alltag",
    "nav.download": "Download",
    "nav.home": "Start",
    "nav.privacy": "Datenschutz",
    "nav.terms": "Bedingungen",
    "hero.kicker": "Ein Foto wird zu einem kleinen Freund.",
    "hero.title": "Dein Haustier,<br />immer bei dir.",
    "hero.lead": "Mongchi macht aus einem Lieblingsfoto deines Hundes oder deiner Katze einen kleinen Pixelbegleiter, um den du dich kümmerst, mit dem du chattest, spielst und Erinnerungen sammelst.",
    "hero.primary": "Mongchi entdecken",
    "hero.secondary": "So geht’s los",
    "hero.release": "Bald für iOS und Android.",
    "hero.photoCaption": "Ein Herzensfoto",
    "marquee": "KENNENLERNEN · VERSORGEN · CHATTEN · SPIELEN · ERINNERUNGEN SAMMELN · NÄHERKOMMEN",
    "photo.kicker": "So geht’s los",
    "photo.title": "Ein Lieblingsfoto.<br />Ein kleiner Pixelbegleiter.",
    "photo.lead": "Wähle ein klares Foto aus und entdecke deinen Hund oder deine Katze als kleinen Pixelbegleiter.",
    "photo.caption": "Dein Lieblingsfoto",
    "photo.note": "Aus deinem Foto entsteht dein Pixelbegleiter.",
    "photo.policy": "Datenschutzerklärung lesen",
    "care.kicker": "Jeden Tag ein bisschen näher",
    "care.title": "Euer Alltag,<br />voller kleiner Momente.",
    "care.lead": "Echte Einblicke in die App und ihre liebevoll gestaltete Pixelwelt.",
    "care.gentleTitle": "Ganz ohne Druck",
    "care.gentleBody": "Auch wenn du mal einen Tag aussetzt, ist alles gut.",
    "care.chatTitle": "Chat mit Persönlichkeit",
    "care.chatBody": "Liebevolle Antworten im Chat – von KI erstellt.",
    "care.memoryTitle": "Kleine Erinnerungen",
    "care.memoryBody": "Fundstücke von Spaziergängen, Gesichtsausdrücke und Briefe – nach und nach gesammelt.",
    "download.kicker": "Mongchi kommt bald",
    "download.title": "Dein Pixelbegleiter. Immer dabei.",
    "download.lead": "Für kleine Pausen im Alltag und das schöne Gefühl, deinem Liebling nah zu sein.",
    "download.coming": "Demnächst verfügbar:",
    "download.meta": "Kostenloser Download · iOS und Android",
    "footer.tagline": "Mongchi – Dein Haustier als Pixelbegleiter",
    "footer.support": "Support",
    "footer.legalTitle": "Rechtliches",
    "footer.privacy": "Datenschutzerklärung",
    "footer.terms": "Nutzungsbedingungen",
    "footer.delete": "Daten löschen",
    "footer.language": "Sprache",
    "legal.back": "← Zurück zu Mongchi",
    "legal.eyebrow": "Rechtliches",
    "legal.overview": "Dieselbe verständliche Übersicht wie in der App",
    "legal.fullEnglish": "Vollständigen englischen Rechtstext lesen",
    "legal.note": "Diese übersetzte Übersicht entspricht dem Hinweis in der App. Der vollständige englische Text bleibt unten als vollständig veröffentlichte Richtlinie verfügbar. Wende dich an den Support, wenn du Hilfe brauchst.",
    "legal.contact": "Fragen? E-Mail an den Support",
    "privacy.heading": "Mongchi Datenschutzerklärung",
    "privacy.updated": "Veröffentlicht am 12. Juli 2026 · Volltext v1.1",
    "terms.heading": "Mongchi Nutzungsbedingungen",
    "terms.updated": "Veröffentlicht am 12. Juli 2026 · Volltext v1.0",
  },
  "fr-FR": {
    ...ENGLISH,
    "meta.landing.title": "Mongchi – Votre chien ou votre chat en pixels",
    "meta.landing.description": "Avec Mongchi, une photo de votre chien ou de votre chat devient un compagnon en pixels. Prenez-en soin, discutez avec lui grâce à l’IA, jouez et collectionnez vos souvenirs.",
    "meta.privacy.title": "Politique de confidentialité - Mongchi",
    "meta.privacy.description": "Les données traitées par Mongchi, l'utilisation de la photo de votre compagnon et vos choix.",
    "meta.terms.title": "Conditions d'utilisation - Mongchi",
    "meta.terms.description": "Les conditions de Mongchi concernant le contenu IA, les photos, les achats et l'utilisation acceptable.",
    "a11y.skip": "Aller au contenu",
    "a11y.header": "En-tête du site Mongchi",
    "a11y.home": "Accueil Mongchi",
    "a11y.primaryNav": "Navigation principale",
    "a11y.footerNav": "Navigation du pied de page",
    "a11y.language": "Langue du site",
    "a11y.preview": "Aperçu de l'application Mongchi",
    "a11y.activities": "Activités Mongchi",
    "a11y.features": "Fonctionnalités Mongchi",
    "a11y.principles": "Principes Mongchi",
    "a11y.storeOptions": "Téléchargements bientôt disponibles",
    "nav.start": "Le début",
    "nav.life": "La vie ensemble",
    "nav.download": "Télécharger",
    "nav.home": "Accueil",
    "nav.privacy": "Confidentialité",
    "nav.terms": "Conditions",
    "hero.kicker": "Une photo devient un petit compagnon.",
    "hero.title": "Votre compagnon,<br />dans votre téléphone.",
    "hero.lead": "Avec Mongchi, une photo de votre chien ou de votre chat suffit pour donner vie à un petit compagnon en pixels, prêt à partager votre quotidien.",
    "hero.primary": "Découvrir l’appli",
    "hero.secondary": "Voir comment ça marche",
    "hero.release": "Bientôt sur iOS et Android.",
    "hero.photoCaption": "Une photo précieuse",
    "marquee": "RENCONTRE · PETITS SOINS · DISCUSSIONS · JEUX · SOUVENIRS · COMPLICITÉ",
    "photo.kicker": "Pour commencer",
    "photo.title": "Votre photo préférée.<br />Votre compagnon en pixels.",
    "photo.lead": "Choisissez une photo nette de votre chien ou de votre chat, puis découvrez sa version en pixels.",
    "photo.caption": "Votre photo préférée",
    "photo.note": "Votre photo sert à créer votre petit compagnon.",
    "photo.policy": "Lire la politique de confidentialité",
    "care.kicker": "Un monde qui grandit avec vous",
    "care.title": "Ensemble au quotidien,<br />un petit moment après l’autre.",
    "care.lead": "Découvrez de vrais écrans de l’appli et son univers en pixels, entièrement créé à la main.",
    "care.gentleTitle": "À votre rythme",
    "care.gentleBody": "Vous n’ouvrez pas l’appli pendant une journée ? Aucun souci.",
    "care.chatTitle": "Des échanges à son image",
    "care.chatBody": "Ses réponses chaleureuses sont générées par l’IA et inspirées de son profil.",
    "care.memoryTitle": "Petits souvenirs",
    "care.memoryBody": "Les trouvailles de vos balades, ses mimiques et ses lettres enrichissent peu à peu vos souvenirs.",
    "download.kicker": "Mongchi arrive bientôt",
    "download.title": "Emportez son petit univers partout avec vous.",
    "download.lead": "Une appli pensée pour de petites pauses complices et le plaisir de retrouver votre compagnon au quotidien.",
    "download.coming": "Disponible prochainement",
    "download.meta": "Téléchargement gratuit · iOS et Android",
    "footer.tagline": "Mongchi - Votre compagnon vit dans votre téléphone",
    "footer.support": "Assistance",
    "footer.legalTitle": "Mentions légales",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "footer.delete": "Suppression des données",
    "footer.language": "Langue",
    "legal.back": "← Retour à Mongchi",
    "legal.eyebrow": "Mentions légales",
    "legal.overview": "Le même résumé clair que dans l'application",
    "legal.fullEnglish": "Lire le texte juridique complet en anglais",
    "legal.note": "Ce résumé traduit correspond aux informations de l'application. Le texte anglais complet reste disponible ci-dessous comme politique publiée intégrale. Contactez l'assistance si vous avez besoin d'aide.",
    "legal.contact": "Une question ? Écrire à l'assistance",
    "privacy.heading": "Politique de confidentialité de Mongchi",
    "privacy.updated": "Publiée le 12 juillet 2026 · Texte complet v1.1",
    "terms.heading": "Conditions d'utilisation de Mongchi",
    "terms.updated": "Publiées le 12 juillet 2026 · Texte complet v1.0",
  },
  "pt-BR": {
    ...ENGLISH,
    "meta.landing.title": "Mongchi — Seu pet em pixels",
    "meta.landing.description": "O Mongchi transforma uma foto do seu cachorro ou gato em um companheiro em pixels. Cuide dele, converse, brinque e guarde memórias juntos.",
    "meta.privacy.title": "Política de Privacidade - Mongchi",
    "meta.privacy.description": "O que o Mongchi processa, como a foto do seu bichinho é tratada e quais são suas escolhas.",
    "meta.terms.title": "Termos de Serviço - Mongchi",
    "meta.terms.description": "Os termos do Mongchi sobre conteúdo de IA, fotos, compras e uso aceitável.",
    "a11y.skip": "Pular para o conteúdo",
    "a11y.header": "Cabeçalho do site Mongchi",
    "a11y.home": "Início do Mongchi",
    "a11y.primaryNav": "Navegação principal",
    "a11y.footerNav": "Navegação do rodapé",
    "a11y.language": "Idioma do site",
    "a11y.preview": "Prévia do app Mongchi",
    "a11y.activities": "Atividades do Mongchi",
    "a11y.features": "Histórias do Mongchi",
    "a11y.principles": "Princípios do Mongchi",
    "a11y.storeOptions": "Opções de download em breve",
    "nav.start": "Como começa",
    "nav.life": "Vida juntos",
    "nav.download": "Baixar",
    "nav.home": "Início",
    "nav.privacy": "Privacidade",
    "nav.terms": "Termos",
    "hero.kicker": "Uma foto vira um amiguinho em pixels.",
    "hero.title": "Seu bichinho,<br />vivendo no seu celular.",
    "hero.lead": "O Mongchi transforma uma foto do seu cachorro ou gato em um companheiro em pixels. Cuide dele, converse, brinque e guarde as memórias de vocês.",
    "hero.primary": "Quero conhecer",
    "hero.secondary": "Veja como funciona",
    "hero.release": "Em breve para iOS e Android.",
    "hero.photoCaption": "Uma foto especial",
    "marquee": "CONHECER · CUIDAR · CONVERSAR · BRINCAR · GUARDAR MEMÓRIAS · CRIAR LAÇOS",
    "photo.kicker": "Como tudo começa",
    "photo.title": "Sua foto favorita.<br />Seu pet em pixels.",
    "photo.lead": "Escolha uma foto nítida do seu cachorro ou gato e conheça seu novo companheirinho em pixels.",
    "photo.caption": "Sua foto favorita",
    "photo.note": "Sua foto é usada para criar seu pequeno amigo.",
    "photo.policy": "Ler a Política de Privacidade",
    "care.kicker": "Um mundo que cresce com vocês",
    "care.title": "A vida de vocês,<br />um momento de cada vez.",
    "care.lead": "Veja telas reais do app e um universo em pixel art, criado à mão nos mínimos detalhes.",
    "care.gentleTitle": "No seu ritmo",
    "care.gentleBody": "Tudo bem ficar um dia sem entrar.",
    "care.chatTitle": "Conversa com personalidade",
    "care.chatBody": "As respostas são geradas por IA e inspiradas no perfil do seu pet.",
    "care.memoryTitle": "Pequenas lembranças",
    "care.memoryBody": "Descobertas nos passeios, novas expressões e cartas para guardar.",
    "download.kicker": "O Mongchi chega em breve",
    "download.title": "Seu bichinho, sempre por perto.",
    "download.lead": "Feito para pequenos momentos juntos: cuidar, conversar, brincar e guardar memórias.",
    "download.coming": "Em breve",
    "download.meta": "Download grátis · iOS e Android",
    "footer.tagline": "Mongchi - Seu bichinho vive no seu celular",
    "footer.support": "Suporte",
    "footer.legalTitle": "Informações legais",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de Serviço",
    "footer.delete": "Exclusão de dados",
    "footer.language": "Idioma",
    "legal.back": "← Voltar ao Mongchi",
    "legal.eyebrow": "Informações legais",
    "legal.overview": "O mesmo resumo simples mostrado no app",
    "legal.fullEnglish": "Ler o texto jurídico completo em inglês",
    "legal.note": "Este resumo traduzido corresponde ao aviso no app. O texto completo em inglês continua disponível abaixo como a política publicada integral. Fale com o suporte se precisar de ajuda.",
    "legal.contact": "Dúvidas? Envie um e-mail ao suporte",
    "privacy.heading": "Política de Privacidade do Mongchi",
    "privacy.updated": "Publicada em 12 de julho de 2026 · Texto completo v1.1",
    "terms.heading": "Termos de Serviço do Mongchi",
    "terms.updated": "Publicados em 12 de julho de 2026 · Texto completo v1.0",
  },
  "es-MX": {
    ...ENGLISH,
    "meta.landing.title": "Mongchi - Tu mascota vive en tu teléfono",
    "meta.landing.description": "Mongchi convierte una foto de tu perro o gato en una mascota pixel. Cuídala, platica y juega con ella mientras coleccionan recuerdos juntos.",
    "meta.privacy.title": "Política de Privacidad - Mongchi",
    "meta.privacy.description": "Qué datos procesa Mongchi, cómo se trata la foto de tu mascota y cuáles son tus opciones.",
    "meta.terms.title": "Términos de Servicio - Mongchi",
    "meta.terms.description": "Los términos de Mongchi sobre contenido de IA, fotos, compras y uso aceptable.",
    "a11y.skip": "Saltar al contenido",
    "a11y.header": "Encabezado del sitio de Mongchi",
    "a11y.home": "Inicio de Mongchi",
    "a11y.primaryNav": "Navegación principal",
    "a11y.footerNav": "Navegación del pie de página",
    "a11y.language": "Idioma del sitio",
    "a11y.preview": "Vista previa de la app Mongchi",
    "a11y.activities": "Actividades de Mongchi",
    "a11y.features": "Historias de funciones de Mongchi",
    "a11y.principles": "Principios de Mongchi",
    "a11y.storeOptions": "Opciones de descarga próximamente",
    "nav.start": "Cómo empieza",
    "nav.life": "La vida juntos",
    "nav.download": "Descargar",
    "nav.home": "Inicio",
    "nav.privacy": "Privacidad",
    "nav.terms": "Términos",
    "hero.kicker": "Una foto se convierte en un pequeño amigo.",
    "hero.title": "Tu mascota<br />vive en tu teléfono.",
    "hero.lead": "Mongchi convierte una foto de tu perro o gato en su versión pixel para cuidarla, platicar y jugar con ella, y coleccionar recuerdos juntos.",
    "hero.primary": "Quiero Mongchi",
    "hero.secondary": "Ver cómo empieza",
    "hero.release": "Próximamente en iOS y Android.",
    "hero.photoCaption": "Una foto especial",
    "marquee": "CONOCER · CUIDAR · PLATICAR · JUGAR · CREAR RECUERDOS · ESTAR MÁS CERCA",
    "photo.kicker": "Cómo empieza",
    "photo.title": "Una foto de tu mascota.<br />Su versión pixel.",
    "photo.lead": "Elige una foto clara de tu perro o gato y conoce a su versión pixel en Mongchi.",
    "photo.caption": "Tu foto favorita",
    "photo.note": "Tu foto se usa para crear a tu pequeño amigo.",
    "photo.policy": "Consulta la política de privacidad.",
    "care.kicker": "Un mundo que crece contigo",
    "care.title": "Juntos cada día,<br />momento a momento.",
    "care.lead": "Conoce las pantallas reales de la app y su mundo pixel creado a mano.",
    "care.gentleTitle": "A tu ritmo",
    "care.gentleBody": "No pasa nada si un día no entras.",
    "care.chatTitle": "Chat con personalidad",
    "care.chatBody": "Las respuestas se generan con IA y se inspiran en el perfil de tu mascota.",
    "care.memoryTitle": "Pequeños recuerdos",
    "care.memoryBody": "Colecciona hallazgos de los paseos, expresiones y cartas con el paso del tiempo.",
    "download.kicker": "Mongchi llega muy pronto",
    "download.title": "Lleva a tu mascota pixel contigo.",
    "download.lead": "Hecho para compartir ratitos tranquilos y sentir a tu mascota cerca.",
    "download.coming": "Próximamente en",
    "download.meta": "Descarga gratis · iOS y Android",
    "footer.tagline": "Mongchi - Tu mascota vive en tu teléfono",
    "footer.support": "Soporte",
    "footer.legalTitle": "Información legal",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.delete": "Eliminación de datos",
    "footer.language": "Idioma",
    "legal.back": "← Volver a Mongchi",
    "legal.eyebrow": "Información legal",
    "legal.overview": "El mismo resumen claro que aparece en la app",
    "legal.fullEnglish": "Leer el texto legal completo en inglés",
    "legal.note": "Este resumen traducido coincide con el aviso de la app. El texto completo en inglés sigue disponible abajo como la política publicada integral. Comunícate con soporte si necesitas ayuda.",
    "legal.contact": "¿Tienes preguntas? Envía un correo a soporte",
    "privacy.heading": "Política de Privacidad de Mongchi",
    "privacy.updated": "Publicada el 12 de julio de 2026 · Texto completo v1.1",
    "terms.heading": "Términos de Servicio de Mongchi",
    "terms.updated": "Publicados el 12 de julio de 2026 · Texto completo v1.0",
  },
};

function normalizeLocale(rawLocale) {
  const value = String(rawLocale || "").replace("_", "-").toLowerCase();
  if (value.startsWith("ko")) return "ko-KR";
  if (value.startsWith("ja")) return "ja-JP";
  if (value.startsWith("zh")) return "zh-TW";
  if (value.startsWith("de")) return "de-DE";
  if (value.startsWith("fr")) return "fr-FR";
  if (value.startsWith("pt")) return "pt-BR";
  if (value.startsWith("es")) return "es-MX";
  return "en-US";
}

function initialLocale() {
  const requested = new URL(window.location.href).searchParams.get("lang");
  if (requested) return normalizeLocale(requested);

  const saved = window.localStorage.getItem("mongchi.websiteLocale");
  if (saved) return normalizeLocale(saved);

  for (const locale of window.navigator.languages || [window.navigator.language]) {
    const normalized = normalizeLocale(locale);
    if (normalized !== "en-US" || String(locale).toLowerCase().startsWith("en")) return normalized;
  }
  return "en-US";
}

function copyFor(locale) {
  return COPY[locale] || COPY["en-US"];
}

function localizedSeoUrl(locale, page) {
  const url = new URL(PAGE_PATHS[page] || "/", SEO_ORIGIN);
  if (locale !== "en-US") url.searchParams.set("lang", locale);
  return url.toString();
}

function updateSeoMetadata(locale, page, copy) {
  const title = copy[`meta.${page}.title`];
  const description = copy[`meta.${page}.description`];
  const pageUrl = localizedSeoUrl(locale, page);

  document.querySelectorAll("[data-seo-title]").forEach((element) => {
    element.setAttribute("content", title);
  });
  document.querySelectorAll("[data-seo-description]").forEach((element) => {
    element.setAttribute("content", description);
  });
  document.querySelectorAll("[data-seo-url]").forEach((element) => {
    element.setAttribute("content", pageUrl);
  });
  document.querySelectorAll("[data-seo-locale]").forEach((element) => {
    element.setAttribute("content", OG_LOCALES[locale] || OG_LOCALES["en-US"]);
  });
  document.querySelectorAll("[data-seo-canonical]").forEach((element) => {
    element.setAttribute("href", pageUrl);
  });
}

function updateLocalizedLinks(locale) {
  document.querySelectorAll("a[data-localized-link]").forEach((link) => {
    const originalHref = link.dataset.baseHref || link.getAttribute("href");
    if (!originalHref || originalHref.startsWith("#") || originalHref.startsWith("mailto:")) return;
    link.dataset.baseHref = originalHref;
    const url = new URL(originalHref, window.location.origin);
    url.searchParams.set("lang", locale);
    link.setAttribute("href", `${url.pathname}${url.search}${url.hash}`);
  });
}

function updateCampaignImages(locale) {
  const assetRoot = locale === "en-US"
    ? "/assets/campaign"
    : `/assets/campaign/${locale}`;

  document.querySelectorAll("[data-campaign-poster]").forEach((picture) => {
    const slug = picture.dataset.campaignPoster;
    if (!slug) return;

    const source = picture.querySelector("source");
    const image = picture.querySelector("img");
    const small = `${assetRoot}/${slug}-360.webp`;
    const large = `${assetRoot}/${slug}-720.webp`;

    source?.setAttribute("srcset", `${small} 360w, ${large} 720w`);
    if (source && image?.getAttribute("sizes")) {
      source.setAttribute("sizes", image.getAttribute("sizes"));
    }
    if (image) {
      image.setAttribute("src", large);
      image.setAttribute("srcset", `${small} 360w, ${large} 720w`);
    }
  });
}

function renderLanguageMenus(locale) {
  const activeLocale = LOCALES.find(({ code }) => code === locale) || LOCALES[0];

  document.querySelectorAll("[data-language-menu]").forEach((menu) => {
    menu.querySelectorAll("[data-language-current]").forEach((label) => {
      label.textContent = activeLocale.label;
    });
    menu.querySelectorAll("[data-language-current-short]").forEach((label) => {
      label.textContent = activeLocale.short;
    });

    const panel = menu.querySelector("[data-language-options]");
    if (!panel) return;

    if (panel.children.length === 0) {
      LOCALES.forEach(({ code, label, short }) => {
        const option = document.createElement("button");
        option.type = "button";
        option.className = "language-menu__option";
        option.dataset.localeOption = code;
        option.setAttribute("role", "option");

        appendTextElement(option, "span", "language-menu__option-label", label);
        appendTextElement(option, "span", "language-menu__option-code", short);
        panel.append(option);
      });
    }

    panel.querySelectorAll("[data-locale-option]").forEach((option) => {
      const selected = option.dataset.localeOption === locale;
      option.setAttribute("aria-selected", String(selected));
      option.tabIndex = 0;
    });
  });
}

function applyCopy(locale, page) {
  const copy = copyFor(locale);
  document.documentElement.lang = locale;
  document.body.dataset.locale = locale;
  document.title = copy[`meta.${page}.title`];

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const translated = copy[element.dataset.i18n];
    if (translated) element.textContent = translated;
  });

  document.querySelectorAll("[data-i18n-html]").forEach((element) => {
    const translated = copy[element.dataset.i18nHtml];
    if (translated) element.innerHTML = translated;
  });

  document.querySelectorAll("[data-i18n-attr]").forEach((element) => {
    const [attribute, key] = element.dataset.i18nAttr.split(":");
    const translated = copy[key];
    if (attribute && translated) element.setAttribute(attribute, translated);
  });

  document.querySelectorAll('[data-i18n-content="description"]').forEach((element) => {
    element.setAttribute("content", copy[`meta.${page}.description`]);
  });

  updateSeoMetadata(locale, page, copy);
  renderLanguageMenus(locale);
  updateLocalizedLinks(locale);
  updateCampaignImages(locale);
  return copy;
}

function appendTextElement(parent, tagName, className, text) {
  const element = document.createElement(tagName);
  if (className) element.className = className;
  element.textContent = text;
  parent.append(element);
  return element;
}

async function renderLegalOverview(page, locale, copy) {
  const container = document.querySelector("[data-legal-overview]");
  if (!container) return;

  const legal = await LEGAL_LOADERS[locale]();
  if (document.body.dataset.locale !== locale) return;
  const content = legal[page];
  const items = Object.values(content.items);
  const sectionKeys = page === "privacy"
    ? [["sharingTitle", "sharingBody"], ["rightsTitle", "rightsBody"], ["childrenTitle", "childrenBody"]]
    : [["useTitle", "useBody"], ["portabilityTitle", "portabilityBody"], ["disclaimerTitle", "disclaimerBody"]];

  container.replaceChildren();
  appendTextElement(container, "p", "legal-overview-label", copy["legal.overview"]);
  appendTextElement(container, "h2", "legal-overview-title", content.title);
  appendTextElement(container, "p", "legal-overview-meta", content.updated);

  const list = document.createElement("ul");
  list.className = "legal-overview-list";
  items.forEach((item) => appendTextElement(list, "li", "", item));
  container.append(list);

  const sections = document.createElement("div");
  sections.className = "legal-overview-sections";
  sectionKeys.forEach(([titleKey, bodyKey]) => {
    const section = document.createElement("section");
    section.className = "legal-overview-card";
    appendTextElement(section, "h3", "", content.sections[titleKey]);
    appendTextElement(section, "p", "", content.sections[bodyKey]);
    sections.append(section);
  });
  container.append(sections);

  const note = appendTextElement(container, "p", "legal-localization-note", copy["legal.note"]);
  note.setAttribute("role", "note");
  const contact = document.createElement("a");
  contact.className = "legal-support-link";
  contact.href = "mailto:lucas@define-you.com";
  contact.textContent = `${copy["legal.contact"]}: lucas@define-you.com`;
  container.append(contact);

  const fullPolicy = document.querySelector("[data-full-english]");
  if (fullPolicy) fullPolicy.open = locale === "en-US";
}

async function setLocale(locale, page, persist = false) {
  const normalized = normalizeLocale(locale);
  if (persist) window.localStorage.setItem("mongchi.websiteLocale", normalized);
  const copy = applyCopy(normalized, page);
  if (page === "privacy" || page === "terms") await renderLegalOverview(page, normalized, copy);
}

export async function initI18n(page) {
  const locale = initialLocale();
  await setLocale(locale, page);

  document.querySelectorAll("[data-language-menu]").forEach((menu) => {
    menu.addEventListener("toggle", () => {
      if (!menu.open) return;
      document.querySelectorAll("[data-language-menu][open]").forEach((otherMenu) => {
        if (otherMenu !== menu) otherMenu.open = false;
      });
    });

    menu.addEventListener("click", async (event) => {
      const option = event.target.closest("[data-locale-option]");
      if (!option) return;

      const nextLocale = normalizeLocale(option.dataset.localeOption);
      const url = new URL(window.location.href);
      url.searchParams.set("lang", nextLocale);
      window.history.replaceState({}, "", url);
      await setLocale(nextLocale, page, true);
      menu.open = false;
      menu.querySelector("summary")?.focus();
    });
  });

  document.addEventListener("pointerdown", (event) => {
    if (event.target.closest("[data-language-menu]")) return;
    document.querySelectorAll("[data-language-menu][open]").forEach((menu) => {
      menu.open = false;
    });
  });

  document.addEventListener("keydown", (event) => {
    if (event.key !== "Escape") return;
    document.querySelectorAll("[data-language-menu][open]").forEach((menu) => {
      menu.open = false;
      menu.querySelector("summary")?.focus();
    });
  });
}
